export const moviesData =[ 
    {id:Math.random(),Name:"mrlazd",story:"zazaz",rating:2,image:"Breakingbad.jpg",Descraption:"blalazdaz",vide:<iframe width="560" height="315" src="https://www.youtube.com/embed/HhesaQXLuRY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>} , 
    {id:Math.random(),Name:"dzdad",story:"zazaz",rating:2,image:"Gameof.jpg",Descraption:"ahlabik",vide:<iframe width="560" height="315" src="https://www.youtube.com/embed/rlR4PJn8b8I" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>} ,
    {id:Math.random(),Name:"GAMEOF",story:"zazaz",rating:2,image:"Gameof.jpg",Descraption:"azdajzdajdiazdjiozjd",vide:<iframe width="560" height="315" src="https://www.youtube.com/embed/rlR4PJn8b8I" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> } ,
    {id:Math.random(),Name:"Breakingbad",story:"zazaz",rating:2,image:"Gameof.jpg",Descraption:"dadzadazddazd",vide:<iframe width="560" height="315" src="https://www.youtube.com/embed/rlR4PJn8b8I" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> },
    {id:Math.random(),Name:"Breakingbad",story:"zazaz",rating:2,image:"Gameof.jpg",Descraption:"Ahlabikadz",vide:<iframe width="560" height="315" src="https://www.youtube.com/embed/rlR4PJn8b8I" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    {id:Math.random(),Name:"Breakingbad",story:"zazaz",rating:2,image:"Gameof.jpg",Descraption:"zdazdadd",vide:<iframe width="560" height="315" src="https://www.youtube.com/embed/HhesaQXLuRY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    {id:Math.random(),Name:"Breakingbad",story:"zazaz",rating:2,image:"Gameof.jpg",Descraption:"azdazdaazdack",vide:<iframe width="560" height="315" src="https://www.youtube.com/embed/rlR4PJn8b8I" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>}
]
